version: "3.4"
services:
    media:
        image: openslides-media-dev
        environment:
            - MEDIA_DATABASE_HOST=postgres
            - MEDIA_DATABASE_PORT=5432
            - MEDIA_DATABASE_NAME=openslides
            - MEDIA_DATABASE_PASSWORD_FILE=/run/secrets/postgres_password
        volumes:
            - ./src:/app/src
        ports:
            - 9006:9006
        secrets:
            - postgres_password
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides

secrets:
    postgres_password:
        file: ./secrets/postgres_password
