version: "3"
services:
    media-postgresql:
        image: postgres:11
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
    media:
        image: openslides-media-dev
        environment:
            - MEDIA_DATABASE_HOST=media-postgresql
            - MEDIA_DATABASE_PORT=5432
            - MEDIA_DATABASE_NAME=openslides
            - MEDIA_DATABASE_USER=openslides
            - MEDIA_DATABASE_PASSWORD=openslides
        volumes:
            - ./src:/app/src
        ports:
            - 9006:9006
