version: "3.4"
services:
    media:
        build:
            target: "dev"
            args:
                CONTEXT: "dev"
        image: openslides-media-dev
        environment:
            - MEDIA_DATABASE_HOST=postgres
            - MEDIA_DATABASE_PORT=5432
            - MEDIA_DATABASE_NAME=openslides
            - AUTOUPDATE_HOST=dummy_autoupdate
            - AUTOUPDATE_PORT=9012
            - MESSAGE_BUS_HOST=redis
            - CACHE_HOST=redis
            - OPENSLIDES_DEVELOPMENT=1
            - MEDIA_ADD_TEST_FILES=1
        volumes:
            - ./src:/app/src
        ports:
            - 9006:9006
    dummy_autoupdate:
        build:
            dockerfile: tests/dummy_autoupdate/Dockerfile.dummy_autoupdate
            context: tests/dummy_autoupdate/
        image: openslides-media-dummy-autoupdate
        volumes:
            - ./tests/dummy_autoupdate:/app/dummy_autoupdate
    tests:
        build:
            target: "tests"
            args:
                CONTEXT: "tests"
        image: openslides-media-tests
        environment:
            - OPENSLIDES_DEVELOPMENT=1
        depends_on:
            - media
            - postgres
            - dummy_autoupdate
        volumes:
            - ./tests:/app/tests
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
