name: CI - Build and Test Service

on: [ push, pull_request ]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make run-tests-ci

    - name: Run black
      run: make check-black

    - name: Run isort
      run: make check-isort

    - name: Run flake8
      run: make flake8

    - name: Stop containers
      run: make stop-tests