name: Continuous Integration

on: [ push, pull_request ]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Tests
      uses: Janmtbehrens/OpenSlides/dev/actions/build-service@all-in-one
      with:
        service: media
        context: tests

    - name: Run tests
      run: make run-tests
    
    - name: Run black
      run: make check-black
    
    - name: Run isort
      run: make check-isort
    
    - name: Run flake8
      run: make flake8

    - name: Stop containers
      run: make stop-tests
