name: Continuous Integration

on: [ push, pull_request ]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make run-tests
    - name: Stop containers
      run: make stop-tests
