name: Continuous Integration

on: [ push, pull_request ]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Media Tests als need the dev image
    - name: Build Dev
      uses: Janmtbehrens/OpenSlides/dev/actions/build-service@all-in-one
      with:
        service: media
        context: dev

    - name: Run Test
      uses: Janmtbehrens/OpenSlides/dev/actions/build-and-test-service@all-in-one
      with:
        service: media