name: CI - Build and Test Service

on: [ push, pull_request ]

jobs:
  # This setups and runs the dev/run-tests.sh script
  run-test-script:
    name: Run-tests.sh Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Media Tests als need the dev image
      - name: Build Dev
        uses: OpenSlides/OpenSlides/dev/actions/build-service@main
        with:
          service: media
          context: dev

      - name: Run Test
        uses: OpenSlides/OpenSlides/dev/actions/build-and-test-service@main
        with:
          service: media